---
abstract: 'Hash::Map - Manipulate hashes map like'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Test::Differences: 0
  Test::More: 0
  Test::NoWarnings: 1.03
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Map
provides:
  Hash::Map:
    file: lib/Hash/Map.pm
    version: 0.008
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Carp: 0
  Clone: 0
  Perl6::Export::Attrs: 0
  Scalar::Util: 0
  Try::Tiny: 0
  perl: 5.006
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.008
